version: "3.3"

services: 
  db:
    image: kartoza/postgis:latest
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASS: fla81
      POSTGRES_MULTIPLE_EXTENSIONS: postgis
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080